### ISSUE TITLE
Create app with npx doesn't working 

### ISSUE THREAD

**Issue by frantisekpetko** [alirezakay/rp-app#1]
Greetings, npx doesn't working when I want create app. I getting this error on the windows: 

```
path of rp-app: C:\Users\Derid\AppData\Roaming\npm\node_modules\rp-app\cli.js

[rp-app-cli] is running...
Creating directory `x` And Initializing
Please wait
It might take several minutes!

{ Error: Command failed: mkdir x && cd ./x && npm install rp-app-core --no-save --prefix ./ && cp -rf ./node_modules/rp-app-core/. ./ &&  rm -rf ./node_modules/rp-app-core
A subdirectory or file x already exists.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'mkdir x && cd ./x && npm install rp-app-core --no-save --prefix ./ && cp -rf ./node_modules/rp-app-core/. ./ &&  rm -rf ./node_modules/rp-app-core' }
```

Please fix this, I wanna use Your work/app.

**Comment by alirezakay** [comment]
Hi František Petko,

This error is raised because you have a directory named "x":
***A subdirectory or file x already exists.***

Please delete that directory and test it again, if a new error occurred, just let me know here.

@frantisekpetko

**Comment by frantisekpetko** [comment]
Okay, my fault. But error is still .. 

```
{ Error: Command failed: mkdir cra-php-app && cd ./cra-php-app && npm install rp-app-core --no-save --prefix ./ && cp -rf ./node_modules/rp-app-core/. ./ &&  rm -rf ./node_modules/rp-app-core
'cp' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'mkdir cra-php-app && cd ./cra-php-app && npm install rp-app-core --no-save --prefix ./ && cp -rf ./node_modules/rp-app-core/. ./ &&  rm -rf ./node_modules/rp-app-core' }
```

**Comment by alirezakay** [comment]
@frantisekpetko 
Okay I'll fix it as soon as possible

Thanks for announcing this issue.

**Comment by frantisekpetko** [comment]
Thanks.

**Comment by alirezakay** [comment]
@frantisekpetko 

I just checked it out using `npx` command on **windows 10**
And it worked correctly:
```
npx rp-app create rptest
```

- Which windows OS do you have?

- What's your npx version?

- Is the npx command installed globally?

- Do you have `git bash` software installed on your windows?


Please answer the above questions.

for checking npx version:
```
npx --version
```

**Comment by alirezakay** [comment]
![image](https://user-images.githubusercontent.com/20626510/51425377-7f19a980-1bf0-11e9-86b7-1c13a07ff79c.png)

**Comment by frantisekpetko** [comment]
Thank you a lot! Everything is working. I tried classic cmd before instead of git bash.
